In [1]:
#Connect to mysql
import pymysql
import pandas as pd
import numpy as np
conn=pymysql.connect(host='localhost',port=int(3308),user='root',passwd='',db='fidness')

In [2]:
#select user table
df=pd.read_sql_query("SELECT * FROM fid_carte_fidelite ",conn)
df.head()

,id_admin_creation,code,montant_achat (DT),id_marque,date_debut,date_expiration,id,nom,date_creation
0,1,hafsa,92,16,2021-08-30 00:00:01,2021-10-06 23:59:59,1,hafsa,2021-08-30 17:22:59
1,1,carte fidelite looh,54,29,2021-09-07 00:00:01,2021-10-30 23:59:59,2,carte fidelité looh,2021-09-07 11:02:00
2,1,carte de fidelite ms marion,91,33,2021-09-07 00:00:01,2021-09-30 23:59:59,3,carte de fidelité ms. marion,2021-09-07 20:31:48
3,1,carte de fidelite khalta,71,2,2021-09-08 00:00:01,2022-03-31 23:59:59,4,carte de fidelité khalta,2021-09-08 16:33:48
4,1,mon bijou macaron,66,38,2021-09-08 00:00:01,2021-12-31 23:59:59,5,carte de fidelité mon bijou macaron,2021-09-08 21:36:55

In [3]:
#exportiiiing
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:@localhost:3308/fid_db')
df.to_sql(name='fid_carte_fidelite',con=engine,if_exists='replace')